---
apiVersion: gcp.crossplane.io/v1alpha1
kind: Provider
metadata:
  namespace: crossplane-system
spec:
  credentialsSecretRef:
    namespace: default
    name: experimental
    key: credentials.json
  projectID: long-disk-191221
