---
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: experimental
  namespace: default
  labels:
    app: wordpress
spec:
  classRef:
    apiVersion: compute.gcp.crossplane.io/v1alpha1
    kind: GKEClusterClass
    name: experimental
  connectionRef:
    apiVersion: gcp.crossplane.io/v1alpha1
    kind: Connection
    name: experimental
  providerRef:
    apiVersion: gcp.crossplane.io/v1alpha1
    kind: Provider
    name: experimental
