---
apiVersion: database.crossplane.io/v1alpha1
kind: MySQLInstance
metadata:
  name: experimental
  namespace: default
  labels:
    app: wordpress
spec:
  engineVersion: "5.7"
  classRef:
    apiVersion: database.gcp.crossplane.io/v1alpha1
    kind: CloudSQLInstanceClass
    name: cloudsqlinstance
  connectionRef:
    apiVersion: gcp.crossplane.io/v1alpha1
    kind: Connection
    name: experimental
  providerRef:
    apiVersion: gcp.crossplane.io/v1alpha1
    kind: Provider
    name: experimental
